### ISSUE TITLE
Some slack channels not showing in the slack trigger

### ISSUE THREAD

**Issue by supportbboxx** [wayscript/feedback#6]
Some of the slack channels are not showing in the slack trigger and was also unable to search the channel.

Add Trigger > Choose Slack Trigger.
Add the Workplace > Choose Channel.

Expected Output:
Be able to search the channel that I want.

![image](https://user-images.githubusercontent.com/57546408/68966567-5a716c80-07d6-11ea-807e-5407c99ca91f.png)

Desktop Information
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.97

**Comment by jeffbuswell** [comment]
Hi @iguinto, thanks for reporting this issue! Do you have any more details on the channels that are missing? Are you a member of these channels? Are they public/private? Anything else that might be unique about them?

FYI - making these dropdowns searchable is on our backlog!

**Comment by supportbboxx** [comment]
Hi @jeffbuswell, Thank you for your reply.
Yes, I am a member. I also tried creating Public/Private channels, and it seems only the old channels are showing in the dropdown.

**Comment by jeffbuswell** [comment]
And if you click the "refresh" button, these channels don't show up either?

<img width="111" alt="Screen Shot 2019-11-20 at 7 11 34 PM" src="https://user-images.githubusercontent.com/31461850/69300976-9edf7c80-0bc9-11ea-9a5e-547a4cb4942d.png">

**Comment by supportbboxx** [comment]
Hi @jeffbuswell , Yes I've clicked that button several times and the number of the channels remains the same.

**Comment by supportbboxx** [comment]
Any update please?

**Comment by jeffbuswell** [comment]
@iguinto Apologies for the delayed reply. I believe you were hitting a limit on the number of channels shown in the dropdown. We just pushed an update to the site. Can you please refresh the list and see if the channel you are looking for is present?

**Comment by supportbboxx** [comment]
Hi @jeffbuswell,

Thank you so much. It's all good now.

**Comment by vbinimelis** [comment]
Hi @jeffbuswell ,

I'm facing the same issue. I'm not able to see all the slack channels. I refreshed several times and I still have the same issue.

Could you please help me?

Thanks
